### PR TITLE
Update to React v.18 and use Vite as build tool

### PR DESCRIPTION
**Pull request by vincentdoerig**
As explained on Slack, this PR upgrades the frontend dependencies to their newest versions and now uses Vite as build tool instead of Webpack. The Flask backend is left as is with a slight tweak to serve the frontend files after they were built.

Installing and running the project should be very straight forward and explained in the README, but let me know if you encounter any issues.

### CODE REVIEW

**Comment by zouharvi** [comment]
Managed to run this now and it looks great! Just a note whether the `wekzeug==0.16.1` in the requirements is intentional because there seems to be a conflict.

```
    The user requested werkzeug==0.16.1
    flask 3.0.0 depends on Werkzeug>=3.0.0
```

**Comment by vincentdoerig** [comment]
Ah yes true, I had this error as well. I didn't touch the requirements.txt (these were the original ones Xiaoyu had in the template, but I will make sure to update them in that case!

**Comment by xiaoyu-zhang-betsy** [comment]
I didn't encounter this issue. Maybe I had an older version flask installed on my laptop. @vincentdoerig Feel free to update requirements.txt if you think necessary

**Comment by zouharvi** [comment]
I fixed the requirements in 81417dd.

**Pull request merged**
